name: Deploy ProcessMessage Function App to STG
on:
  workflow_dispatch:
    inputs:
      REF:
        description: Branch from CDCgov/data-exchange-fhir that you want to deploy to the stg environment.
        default: main
        required: true
        type: string
  push:
    branches:
        - main
        - feature/fhir-stg

jobs:
  remote-trigger:
    uses: ./.github/workflows/remote-cd-trigger-template.yml
    with:
      WORKFLOW: build_deploy_processmsg_stg.yml
      REF: ${{ inputs.REF }}
    secrets: inherit
