name: Deploy ProcessMessage Function App

on:
  push:
    branches:
      - main
      - feature/fhir-stg

env:
  AZURE_FUNCTIONAPP_NAME: 'ocio-ede-fhir-processmessage-stg'   
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'source/CDC.DEX.FHIR.Function/CDC.DEX.FHIR.Function.ProcessMessage'
  DOTNET_VERSION: '6.0.x'                   

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: stg
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.PROCESSMSG_FUNAPP_STG_PUBLISH_PROFILE }}

