name: fhir-facade docker image workflow for CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'spikes/fhir-facade/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'spikes/fhir-facade/**'



jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set DNS to Google
      run: | 
       echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf

    - name: Check DNS resolution
      run: cat /etc/resolv.conf

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
       # un comment to use with imagehub
       # imagehub.cdc.gov:6989
       # registry: ${{ secrets.DOCKER_REGISTRY }}
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}

    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag  ${{ vars.DOCKER_PREFIX }}/${{ vars.DOCKER_IMAGE }}:latest
      working-directory: spikes/fhir-facade

    - name: Push Docker image
      # docker tag my-docker-image:latest
      run: |
        docker push  ${{ vars.DOCKER_PREFIX }}/${{ vars.DOCKER_IMAGE }}:latest

      
