name: Deploy Data Export Function to Function App - PRD

on:
  workflow_dispatch:
  push:
    branches:
      - main # or the branch you want to deploy from

env:
   AZURE_FUNCTIONAPP_NAME: 'ocio-ede-prd-fhir-dataexport-fa'
   AZURE_FUNCTIONPACKAGE_PATH: 'source/CDC.DEX.FHIR.Function/CDC.DEX.FHIR.Function.DataExport'
   DOTNET_VERSION: '8.x'

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
 
    - name: Setup .NET ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build and Publish the Project
      shell: pwsh
      run: |
        dotnet publish ${{ env.AZURE_FUNCTIONPACKAGE_PATH }} --configuration Release --output ./publish

    - name: Zip function app files
      run: Compress-Archive -Path ./publish/* -DestinationPath functionapp.zip

    - name: Deploy to Azure Function App
      uses: azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: functionapp.zip
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}